### ISSUE TITLE
Shows, Snapshots and Cues not available in Companion

### ISSUE THREAD

**Issue by gfbrnby** [bitfocus/companion-module-soundcraft-ui#42]
I am using a version of the Soundcraft Ui24R Companion module that doesn't support shows, snapshots and cues. Your help file indicates they are now supported but when I try to install the module I get an error.
![Capture](https://user-images.githubusercontent.com/88475451/134256670-bfeb3f74-51c4-4f0d-876c-0a6bb2d0c0a5.JPG)

**Comment by fmalcher** [comment]
Thanks for the report! The current stable version of Companion does not include the latest version of this module. Please install a beta build or update the specific module manually.
Regarding this `disconnect` error, the fix is already commitet but not included yet. In the meantime, please disable and re-enable the device and it should work. Also see: https://github.com/bitfocus/companion-module-soundcraft-ui/issues/29#issuecomment-811100559
