### ISSUE TITLE
Master password

### ISSUE THREAD

**Issue by sbrongersma** [bitfocus/companion-module-soundcraft-ui#49]
We use a master password on the ui so we can't use this plugin to control it. It would be a nice feature if you also can control a password protected soundcraft.

**Comment by fmalcher** [comment]
Do you have any insights on how the protocol handles the password? It would be great help if you could find out how the pw is transmitted to the mixer.
I will have to implement this in the connection lib first.

**Comment by fmalcher** [comment]
I tested this and set a master password on my Ui24R. interestingly, Companion could still communicate with the mixer as usual. In addition, the raw master password is even published in the mixer state without authentication.
It looks like only the Web Interface handles the password so that you can't use it unless authenticated. The WebSocket API doesn't seem to check the password at all.
Can you please elaborate how the behavior is for you? @sbrongersma

**Comment by fmalcher** [comment]
Closing this because obviously you don't need a master password to use the WebSocket API.
