### ISSUE TITLE
[DISCUSSION] Socket.io instead of native websocket

### ISSUE THREAD

**Issue by fmalcher** [bitfocus/companion-module-soundcraft-ui#7]
I've encountered it a few times now that Companion seems to lose the connection the the mixer (UI24R in my case).
I haven't investigated this any further, but I've seen that this module uses natives Websockets.
However, according to the endpoint URL, the mixer uses socket.io which should be a bit more resilient in terms of reconnecting.
Therefore, I'd suggest to use socket.io in the client module as well since they might play great together. 🙂

**Comment by DachsbauTV** [comment]
Hey just a general note to this:

I've been in contact with soundcraft because I've regularly lost the connection the whole device.

They told me that the device works in UDP only an if connected to a network which also has a Wifi, one should completely avoid the channels 1 , 6 & 9

This actually solved the issue for me.

**Comment by fmalcher** [comment]
I tried to use Socket.io in the connection module. However, the mixer firmware has a super old version of Socket.io. Since client and server must use the exact same protocol version, we must also rely on this super old thing.
I see no reason here to stick with the Socket.io idea, but I used plain WebSockets again.
